language: node_js
node_js:
- node
notifications:
  email: false
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byob_tests;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: BHHk6lvtfayp1QBpo7EkFKpmkarbYrL/uMVIeEhpCi3NZI8gnsNeUN2GOUvQrm3ynsdu0teVY241lst/8wBwzFNkUEDbQaycn/neSu8XNXaiPahfT2ZzDr1Cn3STKa9N+Yy27DHDcqSQFgU5vqbYPbhQ9VI537OvA9LygT79u2vLYw/Ea5njVkbtb7sll3oQ/Uo5Y5lS1QMDhglJk9S3iQbbzYj3/Xo+IJU64XFhdAuDDVuGi4Xn5815E1HvaWqSrT7MhTfRHaNdX6/k4JMEsMxFfojzQbSOa9cD8jIsmnOwjTPiV+ytVZgUmHOGqSLW0VQyicpPYp9t4iSRU2R7A14KND2u6fzDeRDz6HyPcNh8GoqQjJpxXf7PFdLn6XDkSBcVvDwziNXcu/+m92mYAeoGeMBnhFTMPSeLT/26IaLRqWlD0dNIYUc2U9/pDM5IVKKep95HvVxHu2nBuHmY5UGkGYlkbTK4CxrGEB2gcibsQi/3nJZM7HtFK4w3caTGRP2G6FfqLr9247VQ9+xgSD6dfqEZuYAT39URi+HeF/CC9+/WR7e5kzXs9mBfRf1uST9MHXvy3JaACpT3lPCTOUPlYfRS7GHL0y5muL2q0/9YuVZusFXLpTeRO21ZK6D68+3G9DUJzKO2jU1HN1WXru6fABoEewXD2V7USR0OBdc=
  app: colorado-brews
  skip_cleanup: true

